### ISSUE TITLE
How can I contribute to this project?

### ISSUE THREAD

**Issue by ghost** [integrativesoft/electrolite#4]
Hi all.

#### question/feedback
I would like to continue this project. *How can I contribute to this project?*

#### idea
If it's an alternative to electron, maybe the name... could also be different and alternative to electron... have you thought about the name foton?

**Comment by pablocar80** [comment]
Hello! I like the name foton. And yes, contributions are very welcome. Any particular area of interest?

Here are some suggestions:

- Try to run the project in Windows and Linux and verify that it still works.
- Update the version of C# and .NET to the latest version.
- Verify that the 3rd party libraries for support in Windows and Linux still are maintained, update versions if needed.
- Add support for MacOS.
- Create a Hello World application that uses this library and runs cross-platform.

**Comment by pablocar80** [comment]
Oh and I forgot:
- Update the code to change the name to foton
