### ISSUE TITLE
foton with css/ui frameworks?

### ISSUE THREAD

**Issue by ghost** [integrativesoft/electrolite#9]
Hi everyone.

#### concept
I'm thinking of supporting all visual css/ui framework in foton like: Boostrap, Tabler-ui, Skeleton, Bulma, Pure.css, Groundwork, Cardinal, PowertoCSS, Mueller, Bootflat, Flowbite, [fish-ui](https://github.com/myliang/fish-ui).

#### question/feedback
*What do you all think of the idea?*

**Comment by pablocar80** [comment]
Hi, I agree to support all of them, however -- how are they not supported today?

When using Electron, it creates a window that runs a browser on it. Then the browser opens a site hosted by the app itself. So anything that runs in HTML5 will be supported. In our case it's the same situation?
